//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessType
    {
        public ProcessType()
        {
            this.Log_Table = new HashSet<Log_Table>();
        }
    
        public int ID { get; set; }
        public string ProcessName { get; set; }
    
        public virtual ICollection<Log_Table> Log_Table { get; set; }
    }
}
